### Single-layer Neural Network
##### This NN has one linear neuron and is trained to triple an input number.

________
Import everything we need

In [84]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

_________
#### Define a single linear neuron.
This doesn't have an activation function. Normally, would use a sigmoid activation function, maybe?

In [85]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(1,1) # 1 input, 1 output
        
        # if you want more layers:
        # self.fc1 = nn.Linear(1,10) # 1 input, 10 outputs
        # self.fc2 = nn.Linear(10,1) # 10 inputs, 1 output
        
        #if you want to use relu:
        #self.fc1 = nn.Linear(1,1)
        #self.fc2 = nn.Linear(1,1)
        
    def forward(self, x):
        x = self.fc1(x)
            
        # x = self.fc2(self.fc1(x))
        
        # x = F.relu(self.fc2(F.relu(self.fc1(x))))
        return x

In [86]:
net = Net()
# if you want to use a GPU:
# net = net.cuda()
print(list(net.parameters()))

[Parameter containing:
tensor([[0.1101]], requires_grad=True), Parameter containing:
tensor([-0.7248], requires_grad=True)]


_______
#### Chuck a variable through our network:
Create a random int variable to input. Setting requires_grad=True means it's optimizable (the network can optimize it as it learns).

In [87]:
input = Variable(torch.randn(1,1,1), requires_grad=True)
print(input)

tensor([[[0.3242]]], requires_grad=True)


Put it through our network:

In [88]:
out = net(input)
print(out)

tensor([[[-0.6891]]], grad_fn=<AddBackward0>)


Define a loss function and an optimizer:

In [89]:
import torch.optim as optim
def criterion(out, label):
    return (label - out)**2 # loss function here is least squares
# criterion = nn.MSELoss() #relu
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.5)

________
#### Training
Training set: we're trying to teach it to triple a number.

In [90]:
data = [(1,3), (2,6), (3,9), (4,12), (5,15), (6,18)]

Train

In [91]:
for epoch in range(100):
    for i, data2 in enumerate(data):
        X, Y = iter(data2)
        X, Y = Variable(torch.FloatTensor([X]), requires_grad=True), Variable(torch.FloatTensor([Y]), requires_grad=False)
      # if you wannt to use a GPU:
        #X, Y = Variable(torch.FloatTensor([X]), requires_grad=True).cuda(), Variable(torch.FloatTensor([Y])).cuda()
        optimizer.zero_grad()
        outputs = net(X)
        loss = criterion(outputs, Y)
        loss.backward()
        optimizer.step()
        if ((epoch % 10 == 0) and (i % 10 == 0)):
            print("Epoch {} - loss: {}".format(epoch, loss.data[0]))

Epoch 0 - loss: 13.066350936889648
Epoch 10 - loss: 0.012678511440753937
Epoch 20 - loss: 0.004435475915670395
Epoch 30 - loss: 0.001550470944494009
Epoch 40 - loss: 0.0005419873050414026
Epoch 50 - loss: 0.0001894647575682029
Epoch 60 - loss: 6.622997170779854e-05
Epoch 70 - loss: 2.3153070287662558e-05
Epoch 80 - loss: 8.092946700344328e-06
Epoch 90 - loss: 2.8276649572944734e-06


Parameters of Ax+b should be A = 3, b = 0. This is what we have:

In [92]:
list(net.parameters())

[Parameter containing:
 tensor([[2.9998]], requires_grad=True),
 Parameter containing:
 tensor([0.0012], requires_grad=True)]

Now make a prediction:

In [93]:
print(net(Variable(torch.Tensor([[3]]))))

tensor([[9.0006]], grad_fn=<AddmmBackward>)
